const listQurban = [
  {
    id: 1,
    name: "Kambing Apa?",
    price: 3500000,
    href: "#link",
    description: "Umur 3 tahun",
    picture: require("../../../assets/kambing.png"),
    pictureAlt: "Picture description blabla",
  },
  {
    id: 2,
    name: "Kambing Apa?",
    price: 4000000,
    href: "#link",
    description: "Umur 3 tahun",
    picture: require("../../../assets/kambing.png"),
    pictureAlt: "Picture description blabla",
  },
  {
    id: 3,
    name: "Kambing Apa?",
    price: 3750000,
    href: "#link",
    description: "Umur 2 tahun",
    picture: require("../../../assets/kambing.png"),
    pictureAlt: "Picture description blabla",
  },
  {
    id: 4,
    name: "Kambing Apa?",
    price: 4225000,
    href: "#link",
    description: "Umur 3 tahun",
    picture: require("../../../assets/kambing.png"),
    pictureAlt: "Picture description blabla",
  },
  {
    id: 5,
    name: "Kambing Apa?",
    price: 4500000,
    href: "#link",
    description: "Umur 2,5 tahun",
    picture: require("../../../assets/kambing.png"),
    pictureAlt: "Picture description blabla",
  },
  {
    id: 6,
    name: "Kambing Apa?",
    price: 3864000,
    href: "#link",
    description: "Umur 3 tahun",
    picture: require("../../../assets/kambing.png"),
    pictureAlt: "Picture description blabla",
  },
  {
    id: 7,
    name: "Kambing Apa?",
    price: 4567000,
    href: "#link",
    description: "Umur 4 tahun",
    picture: require("../../../assets/kambing.png"),
    pictureAlt: "Picture description blabla",
  },
  {
    id: 8,
    name: "Kambing Apa?",
    price: 4728500,
    href: "#link",
    description: "Umur 3 tahun",
    picture: require("../../../assets/kambing.png"),
    pictureAlt: "Picture description blabla",
  },
];

export default listQurban;
